name = "d1-connect"
main = "cloudflare/worker.js"
compatibility_date = "2024-05-11"

# Binding for D1 database
[[d1_databases]]
binding = "DB"
database_name = "portfolio-messages-db"
database_id = "a8f9ae11-d30f-4376-9d55-525f246032b6"