name: Deno Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Not using yarn? Change `yarn install` to `npm ci` or `pnpm i`
      - name: Install dependencies
        run: yarn install

      # Not using yarn? Change `npm run build` to `yarn build` or `pnpm run build`
      - name: Build Astro
        run: yarn build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: my-deno-project # TODO: replace with Deno Deploy project name
          entrypoint: server/entry.mjs
          root: dist